import json

def create_notebook():
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Leaf Segmentation Test Notebook\n",
                    "\n",
                    "This notebook iterates through three leaf images (one for each veg type), visualizes each image in 3 color spaces (RGB, CIELAB, HSV) for each channel, performs 5D color PCA (plotting a bar chart of explained variance for each component), applies Otsu's thresholding, and draws contours representing the final segmented leaves."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import cv2\n",
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "import os\n",
                    "\n",
                    "%matplotlib inline"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Select Representative Leaf Images\n",
                    "\n",
                    "We select one image from each vegetable type directory (`veg_1`, `veg_2`, `veg_3`)."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "img_paths = [\n",
                    "    'leaf-image/veg_1/IMG_7993.JPG',\n",
                    "    'leaf-image/veg_2/IMG_7995.JPG',\n",
                    "    'leaf-image/veg_3/IMG_7997.JPG'\n",
                    "]\n",
                    "\n",
                    "for path in img_paths:\n",
                    "    if os.path.exists(path):\n",
                    "        print(f\"Verified image: {path}\")\n",
                    "    else:\n",
                    "        print(f\"Error: {path} not found.\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Processing Pipeline\n",
                    "\n",
                    "For each leaf image:\n",
                    "1. **Visualize in 3 Color Spaces (each channel)**: RGB, CIELAB, HSV.\n",
                    "2. **Compute 5D PCA**: Features ($L^*, a^*, b^*, S, H$), project onto PC1, apply polarity correction, and scale to 0-255.\n",
                    "3. **Plot Explained Variance**: Plot a bar chart of variance ratios for the components.\n",
                    "4. **Otsu Thresholding**: Apply Otsu's algorithm to obtain binary mask, then clean up using mathematical morphology.\n",
                    "5. **Contour Overlay**: Find external contours and draw them in green on the original image."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "for idx, path in enumerate(img_paths):\n",
                    "    print(f\"\\n\" + \"=\"*60)\n",
                    "    print(f\"Processing Image {idx+1}: {path}\")\n",
                    "    print(\"=\"*60)\n",
                    "    \n",
                    "    # 1. Read Image\n",
                    "    img_bgr = cv2.imread(path)\n",
                    "    if img_bgr is None:\n",
                    "        print(f\"Could not load {path}\")\n",
                    "        continue\n",
                    "        \n",
                    "    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)\n",
                    "    img_lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2Lab)\n",
                    "    img_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)\n",
                    "    \n",
                    "    # Split channels\n",
                    "    r, g, b = cv2.split(img_rgb)\n",
                    "    l, a, b_lab = cv2.split(img_lab)\n",
                    "    h, s, v = cv2.split(img_hsv)\n",
                    "    \n",
                    "    # Visualize Channels in 3 Color Spaces\n",
                    "    fig, axes = plt.subplots(3, 3, figsize=(15, 12))\n",
                    "    \n",
                    "    # Row 1: R, L*, H\n",
                    "    axes[0, 0].imshow(r, cmap='gray')\n",
                    "    axes[0, 0].set_title('RGB: Red')\n",
                    "    axes[0, 0].axis('off')\n",
                    "    \n",
                    "    axes[0, 1].imshow(l, cmap='gray')\n",
                    "    axes[0, 1].set_title('CIELAB: L* (Lightness)')\n",
                    "    axes[0, 1].axis('off')\n",
                    "    \n",
                    "    axes[0, 2].imshow(h, cmap='gray')\n",
                    "    axes[0, 2].set_title('HSV: Hue')\n",
                    "    axes[0, 2].axis('off')\n",
                    "    \n",
                    "    # Row 2: G, a*, S\n",
                    "    axes[1, 0].imshow(g, cmap='gray')\n",
                    "    axes[1, 0].set_title('RGB: Green')\n",
                    "    axes[1, 0].axis('off')\n",
                    "    \n",
                    "    axes[1, 1].imshow(a, cmap='gray')\n",
                    "    axes[1, 1].set_title('CIELAB: a* (Green-Red)')\n",
                    "    axes[1, 1].axis('off')\n",
                    "    \n",
                    "    axes[1, 2].imshow(s, cmap='gray')\n",
                    "    axes[1, 2].set_title('HSV: Saturation')\n",
                    "    axes[1, 2].axis('off')\n",
                    "    \n",
                    "    # Row 3: B, b*, V\n",
                    "    axes[2, 0].imshow(b, cmap='gray')\n",
                    "    axes[2, 0].set_title('RGB: Blue')\n",
                    "    axes[2, 0].axis('off')\n",
                    "    \n",
                    "    axes[2, 1].imshow(b_lab, cmap='gray')\n",
                    "    axes[2, 1].set_title('CIELAB: b* (Blue-Yellow)')\n",
                    "    axes[2, 1].axis('off')\n",
                    "    \n",
                    "    axes[2, 2].imshow(v, cmap='gray')\n",
                    "    axes[2, 2].set_title('HSV: Value')\n",
                    "    axes[2, 2].axis('off')\n",
                    "    \n",
                    "    plt.suptitle(f\"Color Space Channels - Image {idx+1} ({os.path.basename(path)})\", fontsize=16)\n",
                    "    plt.tight_layout()\n",
                    "    plt.show()\n",
                    "    \n",
                    "    # 2. Perform 5D PCA\n",
                    "    l_flat = l.astype(np.float32).reshape(-1, 1)\n",
                    "    a_flat = a.astype(np.float32).reshape(-1, 1)\n",
                    "    b_flat = b_lab.astype(np.float32).reshape(-1, 1)\n",
                    "    s_flat = s.astype(np.float32).reshape(-1, 1)\n",
                    "    h_flat = h.astype(np.float32).reshape(-1, 1)\n",
                    "    \n",
                    "    color_features = np.hstack((l_flat, a_flat, b_flat, s_flat, h_flat))\n",
                    "    \n",
                    "    mean, eigenvectors, eigenvalues = cv2.PCACompute2(color_features, mean=None)\n",
                    "    projected = cv2.PCAProject(color_features, mean, eigenvectors)\n",
                    "    pc1 = projected[:, 0].reshape(a.shape)\n",
                    "    \n",
                    "    # Polarity Correction\n",
                    "    correlation = np.corrcoef(pc1.ravel(), a.ravel())[0, 1]\n",
                    "    if correlation > 0:\n",
                    "        pc1 = -pc1\n",
                    "        \n",
                    "    pc1_min, pc1_max = pc1.min(), pc1.max()\n",
                    "    pc1_scaled = np.uint8(255 * (pc1 - pc1_min) / (pc1_max - pc1_min + 1e-8))\n",
                    "    \n",
                    "    # Calculate Explained Variance\n",
                    "    total_variance = np.sum(eigenvalues)\n",
                    "    var_ratios = (eigenvalues[:, 0] / total_variance) * 100\n",
                    "    \n",
                    "    # Plot Scree Plot\n",
                    "    plt.figure(figsize=(8, 4.5))\n",
                    "    pc_labels = [f'PC{i+1}' for i in range(len(var_ratios))]\n",
                    "    bars = plt.bar(pc_labels, var_ratios, color=['red', 'blue', 'orange', 'purple', 'brown'], alpha=0.7)\n",
                    "    plt.ylabel('Percentage of Explained Variance (%)')\n",
                    "    plt.title(f'5D PCA Scree Plot (Information Captured per Component) - Image {idx+1}')\n",
                    "    plt.ylim(0, 110)\n",
                    "    for bar in bars:\n",
                    "        yval = bar.get_height()\n",
                    "        plt.text(bar.get_x() + bar.get_width()/2.0, yval + 2, f\"{yval:.2f}%\", ha='center', va='bottom', fontweight='bold')\n",
                    "    plt.grid(axis='y', linestyle='--', alpha=0.5)\n",
                    "    plt.show()\n",
                    "    \n",
                    "    # 3. Apply Otsu Thresholding & Morphology\n",
                    "    ret, thresh = cv2.threshold(pc1_scaled, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)\n",
                    "    print(f\"Otsu threshold value calculated: {ret}\")\n",
                    "    \n",
                    "    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))\n",
                    "    cleaned = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)\n",
                    "    cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_CLOSE, kernel)\n",
                    "    \n",
                    "    # Post-processing: Filter out background/gulley lines geometrically\n",
                    "    contours, _ = cv2.findContours(cleaned, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
                    "    filtered_mask = np.zeros_like(cleaned)\n",
                    "    for cnt in contours:\n",
                    "        area = cv2.contourArea(cnt)\n",
                    "        if area < 100 or area > 150000:\n",
                    "            continue\n",
                    "        x, y, w, h = cv2.boundingRect(cnt)\n",
                    "        aspect_ratio = float(w) / h\n",
                    "        if w > 0.8 * img_bgr.shape[1] or aspect_ratio > 4.0 or aspect_ratio < 0.25:\n",
                    "            continue\n",
                    "        cv2.drawContours(filtered_mask, [cnt], -1, 255, -1)\n",
                    "    cleaned = filtered_mask\n",
                    "    \n",
                    "    # 4. Contour Detection and Overlay\n",
                    "    contours, _ = cv2.findContours(cleaned, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
                    "    \n",
                    "    img_contour = img_rgb.copy()\n",
                    "    cv2.drawContours(img_contour, contours, -1, (0, 255, 0), 2)\n",
                    "    \n",
                    "    # Plot Segmentation Results\n",
                    "    fig, axes = plt.subplots(1, 3, figsize=(18, 6))\n",
                    "    \n",
                    "    axes[0].imshow(pc1_scaled, cmap='gray')\n",
                    "    axes[0].set_title(\"Polarity-Corrected PC1 Image\")\n",
                    "    axes[0].axis('off')\n",
                    "    \n",
                    "    axes[1].imshow(cleaned, cmap='gray')\n",
                    "    axes[1].set_title(\"Otsu Binary Mask (Cleaned)\")\n",
                    "    axes[1].axis('off')\n",
                    "    \n",
                    "    axes[2].imshow(img_contour)\n",
                    "    axes[2].set_title(f\"Segmented Contours ({len(contours)} contours)\")\n",
                    "    axes[2].axis('off')\n",
                    "    \n",
                    "    plt.suptitle(f\"Segmentation Steps & Final Contours - Image {idx+1}\", fontsize=16)\n",
                    "    plt.tight_layout()\n",
                    "    plt.show()"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.11.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }
    
    with open('segmentation-test.ipynb', 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=1)
    print("Successfully generated segmentation-test.ipynb!")

if __name__ == '__main__':
    create_notebook()
